name: Duplicate code

on: pull_request

jobs:
  duplicate-code-check:
    name: Check for duplicate code
    runs-on: ubuntu-20.04
    steps:
      - name: Check for duplicate code
        uses: cs19b005-gautam/se-tool@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directories: "."
